    Private Sub 刷新表格_Click(sender As Object, e As EventArgs) Handles 刷新表格.Click
        Dim swModel As ModelDoc2 = MySwApp.ActiveDoc
        If swModel Is Nothing Then
            MySwApp.SendMsgToUser("当前没有任何文档打开，该程序必须在装配体中运行！")
            Exit Sub
        ElseIf swModel.GetType <> 2 Then
            MySwApp.SendMsgToUser("当前打开的文档不是一个装配体，请打开装配体后再试！")
            Exit Sub
        End If

        Dim swAssyDoc As AssemblyDoc = swModel
        Dim Components = swAssyDoc.GetComponents(False) '顶层true所有false


        ListView1.BeginUpdate()
        ListView1.Clear()
        Dim Colus0 As ColumnHeader = ListView1.Columns.Add("序号")
        Colus0.Width = 30
        Dim Colus1 As ColumnHeader = ListView1.Columns.Add("零件名称")
        Colus1.Width = 200
        Dim Colus2 As ColumnHeader = ListView1.Columns.Add("工程图")
        Colus2.Width = 25
        'Dim Colus3 As ColumnHeader = ListView1.Columns.Add("厚度")
        'Colus3.Width = 40
        Dim Colus4 As ColumnHeader = ListView1.Columns.Add("数量")
        Colus4.Width = 35
        'Dim Colus5 As ColumnHeader = ListView1.Columns.Add("折弯刀数")
        'Colus5.Width = 35

        Dim i As Integer
        For Each swComp As Component2 In Components
            Dim swPart As ModelDoc2 = swComp.GetModelDoc2
            If swPart Is Nothing Then GoTo Ec
            If swPart.GetType <> 1 Then GoTo Ec


            Dim Spath As String = swPart.GetPathName
            Spath = Strings.Left(Spath, Len(Spath) - 7)
            Dim STitle As String = swPart.GetTitle & " * " & swComp.ReferencedConfiguration

            'Columns Items
            For ii = 0 To ListView1.Items.Count - 1
                If ListView1.Items(ii).SubItems(1).Text = STitle Then
                    Dim ir As Integer
                    ir = ListView1.Items(ii).SubItems(3).Text
                    ListView1.Items(ii).SubItems(3).Text = ir + 1
                    GoTo Ec
                End If
            Next

            Dim Item As ListViewItem = ListView1.Items.Add(i)
            Item.SubItems.Add(swPart.GetTitle & " * " & swComp.ReferencedConfiguration)

            If File.Exists(Spath & ".SLDDRW") Then
                Item.SubItems.Add("存在")
            Else
                Item.SubItems.Add("")
            End If

            Item.SubItems.Add(1)
            i = i + 1
Ec:     Next

        ListView1.EndUpdate()
    End Sub
